# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kill9Game < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.2.0/kill9-game_Darwin_x86_64.tar.gz"
      sha256 "91739129a72822b23200accd42678dbd0c680dfdc9028075a5ac55dae2ad83a2"

      define_method(:install) do
        bin.install "kill9-game"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.2.0/kill9-game_Darwin_arm64.tar.gz"
      sha256 "7fd77cdeeed282c3aedb9ea1782306e2b8df882014346d426477d53814dbc8d3"

      define_method(:install) do
        bin.install "kill9-game"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.2.0/kill9-game_Linux_x86_64.tar.gz"
      sha256 "9c7e27d8fb3efe6e71fa023483fe84328598615ddefdacc8692ac81089d4df4e"
      define_method(:install) do
        bin.install "kill9-game"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.2.0/kill9-game_Linux_arm64.tar.gz"
      sha256 "60b830f3163392a9cdc616ca4b9154d7f200775d97cac8b95a537752db05f394"
      define_method(:install) do
        bin.install "kill9-game"
      end
    end
  end
end
