# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kill9Game < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.1.0/kill9-game_Darwin_x86_64.tar.gz"
      sha256 "4088eb60011ae2fc79476e9708d52c2def9f704ad9167977d20ac64090e52f8f"

      define_method(:install) do
        bin.install "kill9-game"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.1.0/kill9-game_Darwin_arm64.tar.gz"
      sha256 "d5cec0df2dd25fb335dcb185ce8719da0eb7798ac97d6c07b10bbc5bdb804d63"

      define_method(:install) do
        bin.install "kill9-game"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.1.0/kill9-game_Linux_x86_64.tar.gz"
      sha256 "1c0d01654d3dd4a0e1450ee285c8f67da403fe568a7fb283b2789af72430d25f"
      define_method(:install) do
        bin.install "kill9-game"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuskey8/kill9-game/releases/download/v0.1.0/kill9-game_Linux_arm64.tar.gz"
      sha256 "47281c27d232351d084c05cebce642b1090b9b3fbf4571d57a53e83f8a2335c3"
      define_method(:install) do
        bin.install "kill9-game"
      end
    end
  end
end
